[project]
name = "tools-agents"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Dhyan-Shah", email = "dhyanshah15114@gmail.com" }
]
requires-python = ">=3.14"
dependencies = [
    "arxiv>=4.0.1",
    "bs4>=0.0.2",
    "chromadb>=1.5.9",
    "ddgs>=9.16.0",
    "duckdb>=1.5.6",
    "duckduckgo-search>=8.1.1",
    "faiss-cpu>=1.15.1",
    "huggingface-hub>=1.33.0",
    "ipykernel>=7.3.0",
    "langchain>=1.4.3",
    "langchain-chroma>=1.1.0",
    "langchain-community>=0.4.2",
    "langchain-groq>=1.1.3",
    "langchain-huggingface>=1.2.2",
    "langchain-openai>=1.6.6",
    "langchain-text-splitters>=1.1.2",
    "langchainhub>=0.1.21",
    "mysql-connector-python>=26.7.0",
    "numexpr>=2.14.2",
    "openai>=3.20.0",
    "pandas>=3.0.6",
    "pymupdf>=1.28.2",
    "pypdf>=6.19.0",
    "python-dotenv>=1.2.3",
    "pytube>=15.0.0",
    "sentence-transformers>=6.1.0",
    "sqlalchemy>=2.1.1",
    "streamlit>=1.64.0",
    "unstructured>=0.27.10",
    "validators==0.28.1",
    "wikipedia>=1.4.0",
    "youtube-transcript-api>=1.2.4",
]

[project.scripts]
tools-agents = "tools_agents:main"

[build-system]
requires = ["uv_build>=0.12.17,<0.13.0"]
build-backend = "uv_build"
